Repository wecode-bootcamp-korea/18-1st-KKAKKA-backend, pull requests merged in 2021-03, with the labels that each got.

#2 [ 18-1st-KKAKKA-이수진, 이호열 ] models.py - 2차 리뷰 반영 완료! 오타 및 convention 오류 수정 완료
  account/__init__.py
  account/admin.py
  account/apps.py
  account/migrations/0001_initial.py
  account/migrations/0002_auto_20210319_1333.py
  account/migrations/0003_auto_20210319_1546.py
  account/migrations/__init__.py
  account/models.py
  account/tests.py
  account/views.py
  kkakkka/settings.py
  lesson/__init__.py
  lesson/admin.py
  lesson/apps.py
  lesson/migrations/0001_initial.py
  lesson/migrations/0002_lesson_category.py
  lesson/migrations/__init__.py
  lesson/models.py
  lesson/tests.py
  lesson/views.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210319_1333.py
  order/migrations/0003_auto_20210319_1355.py
  order/migrations/0004_auto_20210319_1356.py
  order/migrations/0005_auto_20210319_1546.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210319_1333.py
  product/migrations/0003_auto_20210319_1355.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/0001_initial.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/views.py
  subscription/__init__.py
  subscription/admin.py
  subscription/apps.py
  subscription/migrations/0001_initial.py
  subscription/migrations/0002_auto_20210319_1355.py
  subscription/migrations/__init__.py
  subscription/models.py
  subscription/tests.py
  subscription/views.py
Labels: Status: 리뷰 요청

#3 [ ★urgent / kkakka : 18기 이수진 ] merge 요청
  account/migrations/0001_initial.py
  account/migrations/0002_auto_20210321_2207.py
  account/migrations/0003_auto_20210319_1546.py
  lesson/migrations/0001_initial.py
  lesson/migrations/0002_auto_20210321_2207.py
  lesson/models.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20210321_2207.py
  order/migrations/0003_auto_20210319_1355.py
  order/migrations/0004_auto_20210319_1356.py
  order/migrations/0005_auto_20210319_1546.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20210321_2207.py
  product/migrations/0003_auto_20210319_1355.py
  product/models.py
  review/migrations/0001_initial.py
  subscription/migrations/0001_initial.py
  subscription/migrations/0002_auto_20210319_1355.py
  subscription/models.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#5 account/models.py 수정(unique추가, convnetion수정)
  account/models.py
Labels: Status: 리뷰 요청

#6 [18기 이수진 / kkakka ] Subscription 전체 리스트와 상세페이지 - restful api 리뷰 반영 완료
  kkakkka/urls.py
  order/migrations/0003_auto_20210322_1450.py
  subscription/migrations/0002_subscription_description.py
  subscription/models.py
  subscription/urls.py
  subscription/views.py
Labels: Status: 리뷰 요청

#9 [ 18기 이수진 / kkakka ] Product 리스트 및 상세페이지 - REST API 반영 완료
  kkakkka/urls.py
  order/urls.py
  order/views.py
  product/urls.py
  product/views.py
  subscription/views.py
Labels: Status: 리뷰 요청

#10 [18기 이호열]account url / 컨플릭트 수정
  account/urls.py
  account/validator.py
  account/views.py
  kkakkka/urls.py
  order/migrations/0003_auto_20210324_0942.py
  order/migrations/0004_auto_20210324_1438.py
Labels: Status: 리뷰 요청

#11 [18기 이호열] order.views 주소입력기능추가
  kkakkka/urls.py
  order/models.py
  order/urls.py
  order/views.py
Labels: Status: 수정 요청

#12 [ 18기 이수진 / kkakka ] 주문 테이블 및 구독카트 기능 구현 - 리뷰 반영 완료
  account/views.py
  kkakkka/urls.py
  order/migrations/0003_auto_20210324_0942.py
  order/urls.py
  order/views.py
Labels: Status: 수정 요청

#13 [ ★URGENT ★ // 18기 이수진 ] kkakkka urls.py order 중복 수정
  kkakkka/urls.py
  order/urls.py
  order/views.py
Labels: Status: 리뷰 요청
